name: Gradle Wrapper updates
on:
  schedule:
  #  - cron: "0 00 * * *"
    - cron: "0-59/5 0-23/1 * * *"
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.14
      - name: Gradle update checker
        uses: MeilCli/gradle-update-check-action@v3.0.0
